server:
  port: 8085
spring:
  datasource:
    url: jdbc:h2:file:./DEV_DRONES-373200e7-c296-004f-96a9-410418c98c47/src/main/resources/db/droneDb;AUTO_SERVER=TRUE;MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: Passw0rd
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
app:
  chargeLevelLimit: 25
logging:
  level:
    root: debug
springdoc:
  api-docs:
    path: /api-docs
